package ws.isak.memgamev.fragments;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.Spinner;
import android.widget.Toast;

import ws.isak.memgamev.R;
import ws.isak.memgamev.common.Shared;
import ws.isak.memgamev.engine.ScreenController;
import ws.isak.memgamev.engine.ScreenController.Screen;

/*
 *
 * @author isak
 */

public class PreSurveyFragment extends Fragment implements  View.OnClickListener, AdapterView.OnItemSelectedListener{

    public static final String TAG="Class: PreSurveyFrag";

    public static String ageRange;
    public static String yearsTwitchingRange;
    public static String speciesKnownRange;

    private Spinner ageQuerySpinner;
    private Spinner yearsTwitchingSpinner;
    private Spinner numSpeciesKnownSpinner;

    private Button submitPreSurveyBtn;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        Log.d(TAG, "overriding onCreateView");
        View view = LayoutInflater.from(Shared.context).inflate(R.layout.pre_survey_fragment, container, false);

        //create and populate the age query and years twitching spinners and set their item selection listeners
        ageQuerySpinner = (Spinner) view.findViewById(R.id.pre_survey_age_query_spinner);
        yearsTwitchingSpinner = (Spinner) view.findViewById(R.id.pre_survey_years_twitching_query_spinner);
        numSpeciesKnownSpinner = (Spinner) view.findViewById(R.id.pre_survey_species_known_query_spinner);
        //Log.d (TAG, "ageQuerySpinner: " + ageQuerySpinner);
        //ageQuerySpinner = (Spinner) getActivity().findViewById(R.id.pre_survey_age_query_spinner);
        //create an array adapter using a string array and a default spinner layout
        ArrayAdapter<CharSequence> ageQueryAdapter =  ArrayAdapter.createFromResource(Shared.context, R.array.pre_survey_age_query_list, android.R.layout.simple_spinner_item);
        ArrayAdapter<CharSequence> yearsTwitchingQueryAdapter =  ArrayAdapter.createFromResource(Shared.context, R.array.pre_survey_years_twitching_query_list, android.R.layout.simple_spinner_item);
        ArrayAdapter<CharSequence> speciesKnownQueryAdapter =  ArrayAdapter.createFromResource(Shared.context, R.array.pre_survey_species_known_query_list, android.R.layout.simple_spinner_item);
        //Log.d (TAG, "ageQueryAdapter: " + ageQueryAdapter);
        //specify the layout to use when the list of choices appears
        ageQueryAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        yearsTwitchingQueryAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        speciesKnownQueryAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        //apply the adapter to the spinner
        ageQuerySpinner.setAdapter(ageQueryAdapter);
        yearsTwitchingSpinner.setAdapter(yearsTwitchingQueryAdapter);
        numSpeciesKnownSpinner.setAdapter(speciesKnownQueryAdapter);
        //get submit button and set its click listener
        submitPreSurveyBtn = (Button) view.findViewById(R.id.pre_survey_submit_button);
        submitPreSurveyBtn.setOnClickListener(this);
        return view;
    }

    /*
     * Overriding method OnItemSelected uses a switch to handle the selection of various
     * options from each of the spinners
     */
    @Override
    public void onItemSelected (AdapterView <?> parent, View v, int pos, long id) {
        Log.d(TAG, "overriding method onItemSelected: for each spinner");
        switch (parent.getId()) {
            case R.id.pre_survey_age_query_spinner:
                //TODO Toast.makeText(parent.getContext(), "OnItemSelectedListener : " + parent.getItemAtPosition(pos).toString(), Toast.LENGTH_SHORT).show();
            case R.id.pre_survey_years_twitching_query_spinner:
                //TODO
            case R.id.pre_survey_species_known_query_spinner:
                //TODO
        }
    }

    @Override
    public void onNothingSelected (AdapterView <?> parent) {
        //TODO anything???
        //FIXME unless autogenerated method stub is sufficient, if so why?
    }


    /*
     *  Overriding method onClick handles the behaviour necessary for a click on the
     *  submit survey button
     */

    @Override
    public void onClick (View view) {
        Log.d(TAG, "overriding onClick method: implementing View.OnClickListener");
        switch (view.getId()) {
            case R.id.pre_survey_submit_button:
                //Log.d (TAG, "       : surveySubmitButton");
                submitPreSurvey();
                //TODO case R.id. any other buttons
        }
    }

    public void submitPreSurvey () {
        Log.d (TAG, "method submitPreSurvey: preview data in debugger before storing to UserData");
        //[1] Age
        Spinner ageQuerySpinner = (Spinner) getActivity().findViewById(R.id.pre_survey_age_query_spinner);
        ageRange = ageQuerySpinner.getSelectedItem().toString();
        Log.d (TAG, "                       : ageRange: " + ageRange);
        //[2] Years Twitching
        Spinner yearsTwitchingSpinner = (Spinner) getActivity().findViewById(R.id.pre_survey_years_twitching_query_spinner);
        yearsTwitchingRange = yearsTwitchingSpinner.getSelectedItem().toString();
        Log.d (TAG, "                       : yearsTwitchingRange: " + yearsTwitchingRange);
        //[3] Species Known
        Spinner speciesKnownSpinner = (Spinner) getActivity().findViewById(R.id.pre_survey_species_known_query_spinner);
        speciesKnownRange = speciesKnownSpinner.getSelectedItem().toString();
        Log.d (TAG, "                       : speciesKnownRange: " + speciesKnownRange);

        //TODO when done
        ScreenController.getInstance().openScreen(Screen.MENU_MEM);
    }
}